INSERT INTO PERSON (ID, FIRSTNAME, AGE) VALUES ('1', 'John', 25);
INSERT INTO PERSON (ID, FIRSTNAME, AGE) VALUES ('2', 'Andriy', 30);
INSERT INTO PERSON (ID, FIRSTNAME, AGE) VALUES ('3', 'Ivan', 27);
INSERT INTO PERSON (ID, FIRSTNAME, AGE) VALUES ('4', 'Mike', 32);
INSERT INTO ADDRESS (ID, COUNTRY, CITY, IDPERSON) VALUES ('1', 'USA', 'New York', '1');
INSERT INTO ADDRESS (ID, COUNTRY, CITY, IDPERSON) VALUES ('2', 'Ukraine', 'Lviv', '2');
INSERT INTO ADDRESS (ID, COUNTRY, CITY, IDPERSON) VALUES ('3', 'Poland', 'Warsaw', '3');
INSERT INTO ADDRESS (ID, COUNTRY, CITY, IDPERSON) VALUES ('4', 'Ukraine', 'Kyiv', '2');