INSERT INTO PERSON (AGE, FIRSTNAME, ID) VALUES (25, 'John', '1');
INSERT INTO PERSON (AGE, FIRSTNAME, ID) VALUES (30, 'Andriy', '2');
INSERT INTO PERSON (AGE, FIRSTNAME, ID) VALUES (28, 'Ivan', '3');
SELECT * FROM PERSON;
